### ISSUE TITLE
Todo list for project owner

### ISSUE THREAD

**Issue by pietermarsman** [pdfminer/pdfminer.six#304]
A todo list for someone that is a owner of the pdfminer organization: 

- [x] Make develop the default branch
- [x] Use template for PR and issues
- [x] Setup github pages for documentation
